"""initial schema

Revision ID: f6d406a9c7da
Revises: 
Create Date: 2026-05-16 20:37:52.937518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d406a9c7da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='run_status'), nullable=False),
    sa.Column('listing_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_modifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=64), nullable=False),
    sa.Column('modifier', sa.Float(), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name')
    )
    op.create_table('depreciation_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('curve_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('range_band', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('variant_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('modifier', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Enum('vision', 'history', 'finance', name='agent_name'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='run_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.Enum('GREAT_BUY', 'STRONG_BUY', 'LEAN_BUY', 'NEGOTIATE', 'NEUTRAL', 'LEAN_PASS', 'STRONG_PASS', name='recommendation_enum'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=True),
    sa.Column('history_score', sa.Integer(), nullable=True),
    sa.Column('finance_score', sa.Integer(), nullable=True),
    sa.Column('key_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_reports')
    op.drop_table('agent_results')
    op.drop_table('variant_overrides')
    op.drop_table('depreciation_categories')
    op.drop_table('brand_modifiers')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
