"""Finance agent — vehicle value and cost-of-ownership analysis.

Computation is entirely in Python using the three-layer depreciation model:
    1. Category retention curve   (DB: depreciation_categories)
    2. Brand reliability modifier (DB: brand_modifiers)
    3. Variant/engine override    (DB: variant_overrides)

The LLM is called exactly once — after all numbers are computed — to produce
three plain-language narrative fields. No numbers are generated by the LLM;
every numeric output is deterministic Python.

Entry point:
    run(listing, vision_result, history_result, db) -> FinanceAgentResult
"""

from __future__ import annotations

import logging
from datetime import datetime

import anthropic
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.db_models import BrandModifier, DepreciationCategory, VariantOverride
from app.models.schemas import (
    FinanceAgentResult,
    HistoryAgentResult,
    ListingInput,
    VisionAgentResult,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Lookup tables
# ---------------------------------------------------------------------------

# Typical new MSRP midpoints by category. Used when actual MSRP is unavailable.
# 2021–2023 average base MSRPs — intentionally conservative midpoints.
# Source: Edmunds average transaction price by segment 2022–2023.
TYPICAL_MSRP: dict[str, int] = {
    "sedan": 28_000,
    "luxury_sedan": 55_000,
    "suv": 38_000,
    "luxury_suv": 65_000,
    "truck": 45_000,
    "ev": 52_000,
    "minivan": 40_000,
    "sports": 42_000,
}

# Average annual maintenance cost at vehicle age 4–7 years (RepairPal 2023 data).
# Age multipliers applied in _annual_maintenance().
ANNUAL_MAINTENANCE_BASE: dict[str, int] = {
    "sedan": 650,
    "luxury_sedan": 1_200,
    "suv": 750,
    "luxury_suv": 1_400,
    "truck": 700,
    "ev": 400,   # No oil changes; reduced brake wear from regenerative braking
    "minivan": 700,
    "sports": 900,
}

_LOAN_TERM_MONTHS = 60  # 5-year loan — industry standard for used-car financing

# ---------------------------------------------------------------------------
# Category classification
# ---------------------------------------------------------------------------

_EV_MAKES = {"tesla", "rivian", "lucid", "polestar", "fisker"}
_EV_MODEL_TOKENS = {
    "model 3", "model s", "model x", "model y",
    "leaf", "bolt ev", "bolt euv", "ioniq 5", "ioniq 6",
    "id.4", "id4", "mach-e", "lightning", "lyriq", "taycan", "e-tron",
}

_MINIVAN_TOKENS = {
    "odyssey", "sienna", "pacifica", "grand caravan",
    "carnival", "quest", "sedona", "routan",
}

_TRUCK_TOKENS = {
    "f-150", "f150", "f-250", "f250", "f-350", "f350",
    "silverado", "sierra", "tundra", "tacoma", "ranger",
    "colorado", "canyon", "frontier", "ridgeline", "titan",
    "maverick", "santa cruz",
}
_TRUCK_MAKES = {"ram"}

_SPORTS_TOKENS = {
    "mustang", "camaro", "corvette", "challenger",
    "911", "718", "cayman", "boxster", "gt3", "gt2", "gt4",
    "supra", "gr supra", "370z", "400z",
    "86", "gr86", "brz", "miata", "mx-5",
    "focus rs", "civic type r", "integra type r",
    "m2", "m3", "m4", "m5", "m6",
    "golf r", "cts-v", "viper", "nsx",
}

_SUV_TOKENS = {
    "cr-v", "hrv", "hr-v", "pilot", "passport", "mdx", "rdx",
    "rav4", "highlander", "4runner", "sequoia", "venza",
    "rx", "nx", "gx", "lx", "ux",
    "explorer", "escape", "edge", "bronco", "expedition", "navigator",
    "equinox", "traverse", "tahoe", "suburban", "blazer", "trailblazer",
    "yukon", "acadia", "xt4", "xt5", "xt6", "escalade",
    "x1", "x2", "x3", "x4", "x5", "x6", "x7",
    "gle", "glc", "gls", "glb", "gla",
    "q3", "q4", "q5", "q7", "q8",
    "outback", "forester", "crosstrek", "ascent",
    "atlas", "tiguan", "tucson", "santa fe", "telluride",
    "sorento", "kona", "sportage", "cx-5", "cx-30", "cx-50", "cx-9",
    "rogue", "murano", "pathfinder", "armada",
    "qx50", "qx60", "qx80",
    "range rover", "discovery", "defender",
}

_LUXURY_MAKES = {
    "lexus", "acura", "infiniti", "cadillac", "lincoln", "buick", "genesis",
    "bmw", "mercedes-benz", "mercedes", "audi", "volvo",
    "jaguar", "land rover", "range rover",
    "alfa romeo", "maserati", "bentley", "rolls-royce",
    "ferrari", "lamborghini", "mclaren", "aston martin", "porsche",
}


def classify_category(listing: ListingInput) -> str:
    """Map a vehicle listing to one of the 8 depreciation categories.

    Resolution order matters: EV > minivan > truck > sports > SUV/sedan split.
    The SUV/sedan split is the final step and uses the luxury-make set.
    """
    make = (listing.make or "").lower().strip()
    model = (listing.model or "").lower().strip()

    if make in _EV_MAKES or any(t in model for t in _EV_MODEL_TOKENS):
        return "ev"
    if any(t in model for t in _MINIVAN_TOKENS):
        return "minivan"
    if make in _TRUCK_MAKES or any(t in model for t in _TRUCK_TOKENS):
        return "truck"
    if any(t in model for t in _SPORTS_TOKENS):
        return "sports"

    is_luxury = make in _LUXURY_MAKES

    if any(t in model for t in _SUV_TOKENS):
        return "luxury_suv" if is_luxury else "suv"

    return "luxury_sedan" if is_luxury else "sedan"


# ---------------------------------------------------------------------------
# Financial computations (all pure Python, no LLM)
# ---------------------------------------------------------------------------


def _loan_apr(vehicle_age_years: int) -> float:
    """Estimate typical used-car loan APR by vehicle age.

    Source: Experian State of the Automotive Finance Market Q3 2023 averages.
    """
    if vehicle_age_years <= 3:
        return 0.075
    if vehicle_age_years <= 7:
        return 0.095
    return 0.115


def _monthly_payment(principal: float, annual_rate: float, n_months: int) -> float:
    """Standard loan amortization formula."""
    if principal <= 0:
        return 0.0
    if annual_rate == 0:
        return principal / n_months
    r = annual_rate / 12
    return principal * r * (1 + r) ** n_months / ((1 + r) ** n_months - 1)


def _annual_maintenance(category: str, vehicle_age_years: int) -> int:
    """Estimate annual maintenance cost with an age-band multiplier."""
    base = ANNUAL_MAINTENANCE_BASE.get(category, 700)
    if vehicle_age_years <= 3:
        multiplier = 0.70   # Likely under factory or CPO warranty
    elif vehicle_age_years <= 7:
        multiplier = 1.00   # RepairPal baseline age band
    else:
        multiplier = 1.45   # Aging components — brakes, belts, sensors
    return round(base * multiplier)


def _match_variant(listing: ListingInput, override: VariantOverride) -> bool:
    """Check whether a VariantOverride applies to this listing.

    Matching rules (must all pass):
      - make:             exact lowercase match
      - year:             within [year_from, year_to] if set
      - model_keywords:   at least one keyword found in the model string
      - engine_keywords:  at least one keyword found in model + description
                          (skipped if override.engine_keywords is empty)
    """
    make = (listing.make or "").lower()
    model = (listing.model or "").lower()
    search_text = model + " " + (listing.listing_description or "").lower()

    if override.make != make:
        return False
    if listing.year:
        if override.year_from and listing.year < override.year_from:
            return False
        if override.year_to and listing.year > override.year_to:
            return False
    if not any(kw in model for kw in override.model_keywords):
        return False
    if override.engine_keywords and not any(kw in search_text for kw in override.engine_keywords):
        return False
    return True


def _compute_finance_score(
    asking_price: int,
    market_value: float,
    range_band: float,
    total_repair_high: int,
    vehicle_age_years: int,
    mileage: int,
) -> int:
    """Deterministic 1-10 finance score. Anchored at 7 (fair deal).

    Adjustments:
      Price below market range:  up to +2 (buyer's discount)
      Price above market range:  up to -3 (seller's premium)
      High repair overhead:      up to -2 (repair cost / asking_price ratio)
      Mileage vs. expected:      ±0.5–1.0 (12,000 miles/year average)
    """
    market_low = market_value * (1 - range_band)
    market_high = market_value * (1 + range_band)
    score = 7.0

    if asking_price < market_low:
        discount = (market_low - asking_price) / market_low
        score += min(2.0, discount * 20)
    elif asking_price > market_high:
        premium = (asking_price - market_high) / max(market_high, 1)
        score -= min(3.0, premium * 15)

    if asking_price > 0:
        repair_ratio = total_repair_high / asking_price
        score -= min(2.0, repair_ratio * 8)

    expected_miles = vehicle_age_years * 12_000
    if expected_miles > 0:
        mileage_ratio = mileage / expected_miles
        if mileage_ratio > 1.5:
            score -= 1.0
        elif mileage_ratio > 1.2:
            score -= 0.5
        elif mileage_ratio < 0.5 and vehicle_age_years > 2:
            score += 0.5

    return max(1, min(10, round(score)))


# ---------------------------------------------------------------------------
# LLM narrative generation
# ---------------------------------------------------------------------------

_NARRATIVE_TOOL: dict = {
    "name": "finance_analysis_narrative",
    "description": (
        "Produce plain-language narrative fields for a vehicle finance analysis. "
        "Write for a buyer who is not a finance professional. "
        "Be specific about numbers — include dollar amounts and percentages."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "depreciation_summary": {
                "type": "string",
                "description": (
                    "3-5 sentences. Where this vehicle sits on its depreciation curve, "
                    "its projected values at +1, +3, and +5 years, and what this means "
                    "for the buyer in terms of holding vs. selling."
                ),
            },
            "financing_vs_cash_analysis": {
                "type": "string",
                "description": (
                    "3-4 sentences. Monthly payment at the typical APR for this vehicle "
                    "age, total interest over the loan life, and a clear recommendation "
                    "on whether cash or financing makes more sense in this case."
                ),
            },
            "summary": {
                "type": "string",
                "description": (
                    "2-3 sentences. Plain-language bottom line — does the math work? "
                    "Call out the single most important financial consideration."
                ),
            },
        },
        "required": ["depreciation_summary", "financing_vs_cash_analysis", "summary"],
    },
}


async def _generate_narrative(computed: dict) -> tuple[str, str, str]:
    """Call the LLM to produce narrative fields from pre-computed numbers.

    Uses tool_use to enforce structured JSON output without instructor or parsing.
    Model: claude-haiku — narrative prose is not complex reasoning; use the fast tier.

    Returns:
        (depreciation_summary, financing_vs_cash_analysis, summary)
    Raises:
        anthropic.APIError: on network or API failure (caller handles at agent level)
        RuntimeError: if the model doesn't return the expected tool_use block
    """
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    lines = "\n".join(f"{k}: {v}" for k, v in computed.items())
    user_message = (
        "You are a vehicle finance analyst writing a report for a used-car buyer. "
        "Using the computed data below, produce the three narrative fields.\n\n"
        + lines
    )

    response = await client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=600,
        tools=[_NARRATIVE_TOOL],  # type: ignore[list-item]
        tool_choice={"type": "tool", "name": "finance_analysis_narrative"},
        messages=[{"role": "user", "content": user_message}],
    )

    for block in response.content:
        if block.type == "tool_use" and block.name == "finance_analysis_narrative":
            inp = block.input
            return (
                inp["depreciation_summary"],
                inp["financing_vs_cash_analysis"],
                inp["summary"],
            )

    raise RuntimeError("Finance agent LLM did not return the expected tool_use block")


# ---------------------------------------------------------------------------
# Agent entry point
# ---------------------------------------------------------------------------


async def run(
    listing: ListingInput,
    vision_result: VisionAgentResult | None,
    history_result: HistoryAgentResult | None,
    db: AsyncSession,
) -> FinanceAgentResult:
    """Run the Finance agent.

    Args:
        listing:        Enriched ListingInput from the ingestion pipeline.
        vision_result:  VisionAgentResult if available; None means Vision agent
                        has not run or failed — repair costs default to zero.
        history_result: HistoryAgentResult if available; None means same.
        db:             Async database session from the DI container.

    Returns:
        FinanceAgentResult with all fields populated.

    Raises:
        RuntimeError:       If depreciation seed data is absent from the DB.
        anthropic.APIError: If the LLM call fails.
    """
    current_year = datetime.now().year
    vehicle_age = max(0, current_year - (listing.year or current_year))

    # ------------------------------------------------------------------
    # 1. Classify vehicle into one of the 8 depreciation categories
    # ------------------------------------------------------------------
    category_name = classify_category(listing)
    logger.info(
        "Finance agent: %s %s %s → category '%s'",
        listing.year, listing.make, listing.model, category_name,
    )

    # ------------------------------------------------------------------
    # 2. Load the three DB config layers
    # ------------------------------------------------------------------
    category = await db.scalar(
        select(DepreciationCategory).where(DepreciationCategory.name == category_name)
    )
    if category is None:
        logger.warning(
            "Category '%s' missing from DB — falling back to sedan curve", category_name
        )
        category = await db.scalar(
            select(DepreciationCategory).where(DepreciationCategory.name == "sedan")
        )
    if category is None:
        raise RuntimeError("Depreciation seed data is absent — run init_db() first")

    brand = await db.scalar(
        select(BrandModifier).where(
            BrandModifier.brand_name == (listing.make or "").lower().strip()
        )
    )

    all_variants = (
        await db.execute(
            select(VariantOverride).where(
                VariantOverride.make == (listing.make or "").lower().strip()
            )
        )
    ).scalars().all()

    # ------------------------------------------------------------------
    # 3. Three-layer market value
    # ------------------------------------------------------------------
    curve: list[float] = category.curve_values
    age_idx = min(vehicle_age, 10)

    brand_mod = brand.modifier if brand else 0.0
    matching_variants = [v for v in all_variants if _match_variant(listing, v)]
    variant_mod = sum(v.modifier for v in matching_variants)

    if matching_variants:
        logger.info(
            "Finance agent: %d variant override(s) matched (modifier total = %.3f)",
            len(matching_variants), variant_mod,
        )

    total_modifier = brand_mod + variant_mod
    adjusted_retention = curve[age_idx] * (1.0 + total_modifier)

    typical_msrp = TYPICAL_MSRP[category_name]
    estimated_market_value = round(typical_msrp * adjusted_retention)
    price_delta = listing.asking_price - estimated_market_value

    # ------------------------------------------------------------------
    # 4. Future value projections (+1, +3, +5 years from now)
    # ------------------------------------------------------------------
    def _future_value(years_ahead: int) -> int:
        idx = min(age_idx + years_ahead, 10)
        return round(typical_msrp * curve[idx] * (1.0 + total_modifier))

    projected_1yr = _future_value(1)
    projected_3yr = _future_value(3)
    projected_5yr = _future_value(5)

    # ------------------------------------------------------------------
    # 5. Repair cost aggregation (Vision + History)
    # ------------------------------------------------------------------
    repair_low = (vision_result.total_repair_estimate_low if vision_result else 0) + (
        sum(r.estimated_cost_low for r in history_result.repair_mentions)
        if history_result
        else 0
    )
    repair_high = (vision_result.total_repair_estimate_high if vision_result else 0) + (
        sum(r.estimated_cost_high for r in history_result.repair_mentions)
        if history_result
        else 0
    )

    # ------------------------------------------------------------------
    # 6. Financing math
    # ------------------------------------------------------------------
    apr = _loan_apr(vehicle_age)
    monthly_pmt = _monthly_payment(float(listing.asking_price), apr, _LOAN_TERM_MONTHS)
    total_paid = monthly_pmt * _LOAN_TERM_MONTHS
    total_interest = total_paid - listing.asking_price

    # ------------------------------------------------------------------
    # 7. Annual maintenance estimate
    # ------------------------------------------------------------------
    annual_maintenance = _annual_maintenance(category_name, vehicle_age)

    # ------------------------------------------------------------------
    # 8. Finance score (deterministic)
    # ------------------------------------------------------------------
    finance_score = _compute_finance_score(
        asking_price=listing.asking_price,
        market_value=float(estimated_market_value),
        range_band=category.range_band,
        total_repair_high=repair_high,
        vehicle_age_years=vehicle_age,
        mileage=listing.mileage,
    )

    # ------------------------------------------------------------------
    # 9. LLM narrative (only call — produces three text fields)
    # ------------------------------------------------------------------
    price_delta_pct = (price_delta / max(estimated_market_value, 1)) * 100

    computed_data = {
        "vehicle": f"{listing.year} {listing.make} {listing.model}",
        "asking_price_usd": listing.asking_price,
        "mileage": f"{listing.mileage:,} miles",
        "vehicle_age_years": vehicle_age,
        "expected_mileage_for_age": f"{vehicle_age * 12_000:,} miles",
        "category": category_name,
        "estimated_market_value_usd": f"${estimated_market_value:,}",
        "market_range_usd": (
            f"${round(estimated_market_value * (1 - category.range_band)):,}"
            f" – ${round(estimated_market_value * (1 + category.range_band)):,}"
        ),
        "price_vs_market": (
            f"${abs(price_delta):,} {'above' if price_delta > 0 else 'below'} "
            f"midpoint ({price_delta_pct:+.1f}%)"
        ),
        "projected_value_1yr_usd": f"${projected_1yr:,}",
        "projected_value_3yr_usd": f"${projected_3yr:,}",
        "projected_value_5yr_usd": f"${projected_5yr:,}",
        "total_repair_cost_low_usd": f"${repair_low:,}",
        "total_repair_cost_high_usd": f"${repair_high:,}",
        "effective_all_in_cost_usd": f"${listing.asking_price + repair_high:,}",
        "loan_term": f"{_LOAN_TERM_MONTHS} months (5 years)",
        "loan_apr": f"{apr * 100:.1f}%",
        "monthly_payment_usd": f"${round(monthly_pmt):,}",
        "total_interest_usd": f"${round(total_interest):,}",
        "total_loan_cost_usd": f"${round(total_paid):,}",
        "estimated_annual_maintenance_usd": f"${annual_maintenance:,}",
        "finance_score": f"{finance_score}/10",
    }

    depreciation_summary, financing_vs_cash, summary = await _generate_narrative(computed_data)

    return FinanceAgentResult(
        finance_score=finance_score,
        estimated_market_value=estimated_market_value,
        price_delta=price_delta,
        total_repair_cost_low=repair_low,
        total_repair_cost_high=repair_high,
        depreciation_summary=depreciation_summary,
        financing_vs_cash_analysis=financing_vs_cash,
        projected_annual_maintenance=annual_maintenance,
        summary=summary,
    )
