"""Finance agent — vehicle value and cost-of-ownership analysis.

Computation is entirely in Python using the three-layer depreciation model:
    1. Category retention curve   (DB: depreciation_categories)
    2. Brand reliability modifier (DB: brand_modifiers)
    3. Variant/engine override    (DB: variant_overrides)

The LLM is called twice: once in the independent phase for depreciation and
financing narratives, once in the dependent phase for the overall summary.
No numbers are generated by the LLM; every numeric output is deterministic Python.

Entry points:
    run_independent(listing, db)                                     -> FinancePrecomputed
    run_dependent(listing, precomputed, vision_result, history_result) -> FinanceAgentResult
    run(listing, vision_result, history_result, db)                  -> FinanceAgentResult
        (convenience wrapper — calls both phases in sequence; used outside the graph)
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from typing import TypedDict

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.llm import get_anthropic_client
from app.mcp.client import call_tool
from app.models.db_models import BrandModifier, DepreciationCategory, VariantOverride
from app.models.schemas import (
    FinanceAgentResult,
    HistoryAgentResult,
    ListingInput,
    VisionAgentResult,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Intermediate state — independent phase output consumed by dependent phase
# ---------------------------------------------------------------------------


class FinancePrecomputed(TypedDict):
    """All values computed by run_independent() that run_dependent() needs.

    Travels through LangGraph state between the two Finance nodes.
    Not a Pydantic model — this is internal graph state, not an API contract.
    """

    vehicle_age_years: int
    category_name: str
    typical_msrp: int
    range_band: float
    estimated_market_value: int
    price_delta: int
    projected_1yr: int
    projected_3yr: int
    projected_5yr: int
    annual_maintenance: int
    apr: float
    monthly_payment: float
    total_interest: float
    total_paid: float
    depreciation_summary: str
    financing_vs_cash_analysis: str

# ---------------------------------------------------------------------------
# Lookup tables
# ---------------------------------------------------------------------------

# Typical new MSRP midpoints by category. Used when actual MSRP is unavailable.
# 2021–2023 average base MSRPs — intentionally conservative midpoints.
# Source: Edmunds average transaction price by segment 2022–2023.
TYPICAL_MSRP: dict[str, int] = {
    "sedan": 28_000,
    "luxury_sedan": 55_000,
    "suv": 38_000,
    "luxury_suv": 65_000,
    "truck": 45_000,
    "ev": 52_000,
    "minivan": 40_000,
    "sports": 42_000,
}

# Average annual maintenance cost at vehicle age 4–7 years (RepairPal 2023 data).
# Age multipliers applied in _annual_maintenance().
ANNUAL_MAINTENANCE_BASE: dict[str, int] = {
    "sedan": 650,
    "luxury_sedan": 1_200,
    "suv": 750,
    "luxury_suv": 1_400,
    "truck": 700,
    "ev": 400,   # No oil changes; reduced brake wear from regenerative braking
    "minivan": 700,
    "sports": 900,
}

_LOAN_TERM_MONTHS = 60  # 5-year loan — industry standard for used-car financing

# Respray cost multiplier by paint complexity tier.
# Applied to cosmetic-category Vision repair items only.
# Source: ICAR / Mitchell body shop labor guides.
_PAINT_COMPLEXITY_MULTIPLIER: dict[str, float] = {
    "standard": 1.00,
    "metallic": 1.15,
    "pearl_or_tricoat": 1.35,
}

# ---------------------------------------------------------------------------
# Category classification
# ---------------------------------------------------------------------------

_EV_MAKES = {"tesla", "rivian", "lucid", "polestar", "fisker"}
_EV_MODEL_TOKENS = {
    "model 3", "model s", "model x", "model y",
    "leaf", "bolt ev", "bolt euv", "ioniq 5", "ioniq 6",
    "id.4", "id4", "mach-e", "lightning", "lyriq", "taycan", "e-tron",
}

_MINIVAN_TOKENS = {
    "odyssey", "sienna", "pacifica", "grand caravan",
    "carnival", "quest", "sedona", "routan",
}

_TRUCK_TOKENS = {
    "f-150", "f150", "f-250", "f250", "f-350", "f350",
    "silverado", "sierra", "tundra", "tacoma", "ranger",
    "colorado", "canyon", "frontier", "ridgeline", "titan",
    "maverick", "santa cruz",
}
_TRUCK_MAKES = {"ram"}

_SPORTS_TOKENS = {
    "mustang", "camaro", "corvette", "challenger",
    "911", "718", "cayman", "boxster", "gt3", "gt2", "gt4",
    "supra", "gr supra", "370z", "400z",
    "86", "gr86", "brz", "miata", "mx-5",
    "focus rs", "civic type r", "integra type r",
    "m2", "m3", "m4", "m5", "m6",
    "golf r", "cts-v", "viper", "nsx",
}

_SUV_TOKENS = {
    "cr-v", "hrv", "hr-v", "pilot", "passport", "mdx", "rdx",
    "rav4", "highlander", "4runner", "sequoia", "venza",
    "rx", "nx", "gx", "lx", "ux",
    "explorer", "escape", "edge", "bronco", "expedition", "navigator",
    "equinox", "traverse", "tahoe", "suburban", "blazer", "trailblazer",
    "yukon", "acadia", "xt4", "xt5", "xt6", "escalade",
    "x1", "x2", "x3", "x4", "x5", "x6", "x7",
    "gle", "glc", "gls", "glb", "gla",
    "q3", "q4", "q5", "q7", "q8",
    "outback", "forester", "crosstrek", "ascent",
    "atlas", "tiguan", "tucson", "santa fe", "telluride",
    "sorento", "kona", "sportage", "cx-5", "cx-30", "cx-50", "cx-9",
    "rogue", "murano", "pathfinder", "armada",
    "qx50", "qx60", "qx80",
    "range rover", "discovery", "defender",
}

_LUXURY_MAKES = {
    "lexus", "acura", "infiniti", "cadillac", "lincoln", "buick", "genesis",
    "bmw", "mercedes-benz", "mercedes", "audi", "volvo",
    "jaguar", "land rover", "range rover",
    "alfa romeo", "maserati", "bentley", "rolls-royce",
    "ferrari", "lamborghini", "mclaren", "aston martin", "porsche",
}


def classify_category(listing: ListingInput) -> str:
    """Map a vehicle listing to one of the 8 depreciation categories.

    Resolution order matters: EV > minivan > truck > sports > SUV/sedan split.
    The SUV/sedan split is the final step and uses the luxury-make set.
    """
    make = (listing.make or "").lower().strip()
    model = (listing.model or "").lower().strip()

    if make in _EV_MAKES or any(t in model for t in _EV_MODEL_TOKENS):
        return "ev"
    if any(t in model for t in _MINIVAN_TOKENS):
        return "minivan"
    if make in _TRUCK_MAKES or any(t in model for t in _TRUCK_TOKENS):
        return "truck"
    if any(t in model for t in _SPORTS_TOKENS):
        return "sports"

    is_luxury = make in _LUXURY_MAKES

    if any(t in model for t in _SUV_TOKENS):
        return "luxury_suv" if is_luxury else "suv"

    return "luxury_sedan" if is_luxury else "sedan"


# ---------------------------------------------------------------------------
# Financial computations (all pure Python, no LLM)
# ---------------------------------------------------------------------------


def _loan_apr(vehicle_age_years: int) -> float:
    """Estimate typical used-car loan APR by vehicle age.

    Source: Experian State of the Automotive Finance Market Q3 2023 averages.
    """
    if vehicle_age_years <= 3:
        return 0.075
    if vehicle_age_years <= 7:
        return 0.095
    return 0.115


def _monthly_payment(principal: float, annual_rate: float, n_months: int) -> float:
    """Standard loan amortization formula."""
    if principal <= 0:
        return 0.0
    if annual_rate == 0:
        return principal / n_months
    r = annual_rate / 12
    return principal * r * (1 + r) ** n_months / ((1 + r) ** n_months - 1)


def _annual_maintenance(category: str, vehicle_age_years: int) -> int:
    """Estimate annual maintenance cost with an age-band multiplier."""
    base = ANNUAL_MAINTENANCE_BASE.get(category, 700)
    if vehicle_age_years <= 3:
        multiplier = 0.70   # Likely under factory or CPO warranty
    elif vehicle_age_years <= 7:
        multiplier = 1.00   # RepairPal baseline age band
    else:
        multiplier = 1.45   # Aging components — brakes, belts, sensors
    return round(base * multiplier)


def _match_variant(listing: ListingInput, override: VariantOverride) -> bool:
    """Check whether a VariantOverride applies to this listing.

    Matching rules (must all pass):
      - make:             exact lowercase match
      - year:             within [year_from, year_to] if set
      - model_keywords:   at least one keyword found in the model string
      - engine_keywords:  at least one keyword found in model + description
                          (skipped if override.engine_keywords is empty)
    """
    make = (listing.make or "").lower()
    model = (listing.model or "").lower()
    search_text = model + " " + (listing.listing_description or "").lower()

    if override.make != make:
        return False
    if listing.year:
        if override.year_from and listing.year < override.year_from:
            return False
        if override.year_to and listing.year > override.year_to:
            return False
    if not any(kw in model for kw in override.model_keywords):
        return False
    if override.engine_keywords and not any(kw in search_text for kw in override.engine_keywords):
        return False
    return True


def _compute_finance_score(
    asking_price: int,
    market_value: float,
    range_band: float,
    total_repair_high: int,
    vehicle_age_years: int,
    mileage: int,
) -> int:
    """Deterministic 1-10 finance score. Anchored at 7 (fair deal).

    Adjustments:
      Price below market range:  up to +2 (buyer's discount)
      Price above market range:  up to -3 (seller's premium)
      High repair overhead:      up to -2 (repair cost / asking_price ratio)
      Mileage vs. expected:      ±0.5–1.0 (12,000 miles/year average)
    """
    market_low = market_value * (1 - range_band)
    market_high = market_value * (1 + range_band)
    score = 7.0

    if asking_price < market_low:
        discount = (market_low - asking_price) / market_low
        score += min(2.0, discount * 20)
    elif asking_price > market_high:
        premium = (asking_price - market_high) / max(market_high, 1)
        score -= min(3.0, premium * 15)

    if asking_price > 0:
        repair_ratio = total_repair_high / asking_price
        score -= min(2.0, repair_ratio * 8)

    expected_miles = vehicle_age_years * 12_000
    if expected_miles > 0:
        mileage_ratio = mileage / expected_miles
        if mileage_ratio > 1.5:
            score -= 1.0
        elif mileage_ratio > 1.2:
            score -= 0.5
        elif mileage_ratio < 0.5 and vehicle_age_years > 2:
            score += 0.5

    return max(1, min(10, round(score)))


# ---------------------------------------------------------------------------
# LLM narrative generation
# ---------------------------------------------------------------------------

_INDEPENDENT_NARRATIVE_TOOL: dict = {
    "name": "finance_independent_narrative",
    "description": (
        "Produce depreciation and financing narrative fields for a vehicle finance analysis. "
        "Write for a buyer who is not a finance professional. "
        "Be specific — include dollar amounts and percentages."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "depreciation_summary": {
                "type": "string",
                "description": (
                    "3-5 sentences. Where this vehicle sits on its depreciation curve, "
                    "projected values at +1, +3, and +5 years, and what this means "
                    "for the buyer in terms of holding vs. selling."
                ),
            },
            "financing_vs_cash_analysis": {
                "type": "string",
                "description": (
                    "3-4 sentences. Monthly payment at the typical APR for this vehicle "
                    "age, total interest over the loan life, and a recommendation on "
                    "whether cash or financing makes more sense in this case."
                ),
            },
        },
        "required": ["depreciation_summary", "financing_vs_cash_analysis"],
    },
}

_SUMMARY_TOOL: dict = {
    "name": "finance_summary",
    "description": (
        "Produce a plain-language financial bottom line for a used-car buyer. "
        "Repair costs, price position, and value are already computed — "
        "summarise what they mean together."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "summary": {
                "type": "string",
                "description": (
                    "2-3 sentences. Does the math work? "
                    "Call out the single most important financial consideration. "
                    "If repair costs significantly affect the deal, say so explicitly."
                ),
            },
        },
        "required": ["summary"],
    },
}


async def _generate_independent_narrative(computed: dict) -> tuple[str, str]:
    """LLM call for depreciation_summary and financing_vs_cash_analysis.

    Runs in finance_independent_node — before Vision and History results are known.
    Returns (depreciation_summary, financing_vs_cash_analysis).
    """
    client = get_anthropic_client()
    lines = "\n".join(f"{k}: {v}" for k, v in computed.items())
    user_message = (
        "You are a vehicle finance analyst writing a report for a used-car buyer. "
        "Using the computed data below, produce the two narrative fields.\n\n" + lines
    )
    response = await client.messages.create(  # type: ignore[call-overload]
        model="claude-haiku-4-5-20251001",
        max_tokens=800,
        tools=[_INDEPENDENT_NARRATIVE_TOOL],  # type: ignore[list-item]
        tool_choice={"type": "tool", "name": "finance_independent_narrative"},
        messages=[{"role": "user", "content": user_message}],
    )
    for block in response.content:
        if block.type == "tool_use" and block.name == "finance_independent_narrative":
            dep = block.input.get("depreciation_summary", "Depreciation analysis unavailable.")
            fin = block.input.get("financing_vs_cash_analysis", "Financing analysis unavailable.")
            return dep, fin
    raise RuntimeError("Finance independent LLM did not return expected tool_use block")


async def _generate_summary(computed: dict) -> str:
    """LLM call for the summary field.

    Runs in finance_dependent_node — after repair costs are aggregated.
    Returns the summary string.
    """
    client = get_anthropic_client()
    lines = "\n".join(f"{k}: {v}" for k, v in computed.items())
    user_message = (
        "You are a vehicle finance analyst writing a report for a used-car buyer. "
        "Using the computed data below, produce the summary field.\n\n" + lines
    )
    response = await client.messages.create(  # type: ignore[call-overload]
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        tools=[_SUMMARY_TOOL],  # type: ignore[list-item]
        tool_choice={"type": "tool", "name": "finance_summary"},
        messages=[{"role": "user", "content": user_message}],
    )
    for block in response.content:
        if block.type == "tool_use" and block.name == "finance_summary":
            return block.input.get("summary", "Finance summary unavailable.")
    raise RuntimeError("Finance summary LLM did not return expected tool_use block")


# ---------------------------------------------------------------------------
# Agent entry points
# ---------------------------------------------------------------------------


async def run_independent(
    listing: ListingInput,
    db: AsyncSession,
) -> FinancePrecomputed:
    """Independent phase — runs in parallel with Vision and History nodes.

    Performs all computation that depends only on ListingInput and DB data:
    market value, depreciation projections, financing math, maintenance estimate,
    and the two LLM narrative fields (depreciation_summary, financing_vs_cash_analysis).

    Raises:
        RuntimeError:       If depreciation seed data is absent from the DB.
        anthropic.APIError: If the LLM narrative call fails.
    """
    current_year = datetime.now().year
    vehicle_age = max(0, current_year - (listing.year or current_year))

    # ------------------------------------------------------------------
    # 1. Classify vehicle into one of the 8 depreciation categories
    # ------------------------------------------------------------------
    category_name = classify_category(listing)
    logger.info(
        "Finance agent (independent): %s %s %s → category '%s'",
        listing.year, listing.make, listing.model, category_name,
    )

    # ------------------------------------------------------------------
    # 2. Load the three DB config layers
    # ------------------------------------------------------------------
    category = await db.scalar(
        select(DepreciationCategory).where(DepreciationCategory.name == category_name)
    )
    if category is None:
        logger.warning(
            "Category '%s' missing from DB — falling back to sedan curve", category_name
        )
        category = await db.scalar(
            select(DepreciationCategory).where(DepreciationCategory.name == "sedan")
        )
    if category is None:
        raise RuntimeError("Depreciation seed data is absent — run init_db() first")

    brand = await db.scalar(
        select(BrandModifier).where(
            BrandModifier.brand_name == (listing.make or "").lower().strip()
        )
    )

    all_variants = (
        await db.execute(
            select(VariantOverride).where(
                VariantOverride.make == (listing.make or "").lower().strip()
            )
        )
    ).scalars().all()

    # ------------------------------------------------------------------
    # 3. Three-layer market value
    # ------------------------------------------------------------------
    curve: list[float] = category.curve_values
    age_idx = min(vehicle_age, 10)

    brand_mod = brand.modifier if brand else 0.0
    matching_variants = [v for v in all_variants if _match_variant(listing, v)]
    variant_mod = sum(v.modifier for v in matching_variants)

    if matching_variants:
        logger.info(
            "Finance agent: %d variant override(s) matched (modifier total = %.3f)",
            len(matching_variants), variant_mod,
        )

    total_modifier = brand_mod + variant_mod
    typical_msrp = TYPICAL_MSRP[category_name]
    estimated_market_value = round(typical_msrp * curve[age_idx] * (1.0 + total_modifier))
    price_delta = listing.asking_price - estimated_market_value

    # ------------------------------------------------------------------
    # 4. Future value projections (+1, +3, +5 years from now)
    # ------------------------------------------------------------------
    def _future_value(years_ahead: int) -> int:
        idx = min(age_idx + years_ahead, 10)
        return round(typical_msrp * curve[idx] * (1.0 + total_modifier))

    projected_1yr = _future_value(1)
    projected_3yr = _future_value(3)
    projected_5yr = _future_value(5)

    # ------------------------------------------------------------------
    # 6. Financing math
    # ------------------------------------------------------------------
    apr = _loan_apr(vehicle_age)
    monthly_pmt = _monthly_payment(float(listing.asking_price), apr, _LOAN_TERM_MONTHS)
    total_paid = monthly_pmt * _LOAN_TERM_MONTHS
    total_interest = total_paid - listing.asking_price

    # ------------------------------------------------------------------
    # 7. Annual maintenance estimate
    # ------------------------------------------------------------------
    annual_maintenance = _annual_maintenance(category_name, vehicle_age)

    # ------------------------------------------------------------------
    # 9a. LLM narrative — depreciation and financing text only
    # ------------------------------------------------------------------
    price_delta_pct = (price_delta / max(estimated_market_value, 1)) * 100
    narrative_data = {
        "vehicle": f"{listing.year} {listing.make} {listing.model}",
        "vehicle_age_years": vehicle_age,
        "category": category_name,
        "estimated_market_value_usd": f"${estimated_market_value:,}",
        "market_range_usd": (
            f"${round(estimated_market_value * (1 - category.range_band)):,}"
            f" – ${round(estimated_market_value * (1 + category.range_band)):,}"
        ),
        "price_vs_market": (
            f"${abs(price_delta):,} {'above' if price_delta > 0 else 'below'} "
            f"midpoint ({price_delta_pct:+.1f}%)"
        ),
        "projected_value_1yr_usd": f"${projected_1yr:,}",
        "projected_value_3yr_usd": f"${projected_3yr:,}",
        "projected_value_5yr_usd": f"${projected_5yr:,}",
        "loan_term": f"{_LOAN_TERM_MONTHS} months (5 years)",
        "loan_apr": f"{apr * 100:.1f}%",
        "monthly_payment_usd": f"${round(monthly_pmt):,}",
        "total_interest_usd": f"${round(total_interest):,}",
        "total_loan_cost_usd": f"${round(total_paid):,}",
        "estimated_annual_maintenance_usd": f"${annual_maintenance:,}",
    }
    depreciation_summary, financing_vs_cash = await _generate_independent_narrative(narrative_data)

    return FinancePrecomputed(
        vehicle_age_years=vehicle_age,
        category_name=category_name,
        typical_msrp=typical_msrp,
        range_band=category.range_band,
        estimated_market_value=estimated_market_value,
        price_delta=price_delta,
        projected_1yr=projected_1yr,
        projected_3yr=projected_3yr,
        projected_5yr=projected_5yr,
        annual_maintenance=annual_maintenance,
        apr=apr,
        monthly_payment=monthly_pmt,
        total_interest=total_interest,
        total_paid=total_paid,
        depreciation_summary=depreciation_summary,
        financing_vs_cash_analysis=financing_vs_cash,
    )


async def run_dependent(
    listing: ListingInput,
    precomputed: FinancePrecomputed | None,
    vision_result: VisionAgentResult | None,
    history_result: HistoryAgentResult | None,
) -> FinanceAgentResult:
    """Dependent phase — runs after the three-way join (Vision, History, Finance-independent).

    Aggregates repair costs from both agents, computes the finance score,
    and generates the plain-language summary. If precomputed is None (independent
    phase failed), returns a degraded result with finance_score=None.

    None vision_result or history_result is handled gracefully — repair costs
    from that source default to zero and the summary notes the gap.
    """
    if precomputed is None:
        logger.warning("Finance dependent: precomputed is None — independent phase failed")
        return FinanceAgentResult(
            finance_score=None,
            estimated_market_value=0,
            price_delta=0,
            total_repair_cost_low=0,
            total_repair_cost_high=0,
            depreciation_summary=(
                "Market value computation unavailable — the independent finance phase failed. "
                "Depreciation and financing analysis cannot be provided for this vehicle."
            ),
            financing_vs_cash_analysis="Financing analysis unavailable.",
            projected_annual_maintenance=0,
            summary=(
                "Finance analysis could not be completed because the market value computation "
                "failed. The overall score is based on condition and history data only."
            ),
        )

    # ------------------------------------------------------------------
    # 5. Repair cost aggregation (Vision + History)
    #
    # Per-item MCP normalization: call get_repair_estimate for each item
    # concurrently via asyncio.gather.  If MCP returns available=True, use
    # its cost_low/cost_high; otherwise keep the item's LLM-estimated costs.
    #
    # paint_complexity multiplier: applied after MCP normalization, to
    # cosmetic-category Vision items only.  History items never receive it —
    # paint complexity is a visual property detected exclusively by Vision.
    # ------------------------------------------------------------------

    # Resolve paint complexity multiplier once (Vision items only)
    paint_complexity = vision_result.paint_complexity if vision_result else None
    if paint_complexity is not None:
        paint_mult = _PAINT_COMPLEXITY_MULTIPLIER.get(paint_complexity.value, 1.0)
    else:
        paint_mult = 1.0

    vision_repair_low = 0
    vision_repair_high = 0
    if vision_result:
        vision_items = vision_result.repair_items
        # Fire all MCP calls concurrently
        mcp_tasks = [
            call_tool(
                "get_repair_estimate",
                {
                    "make": listing.make,
                    "model": listing.model,
                    "year": listing.year,
                    "repair_type": item.component,
                },
            )
            for item in vision_items
        ]
        mcp_results = await asyncio.gather(*mcp_tasks)

        for item, mcp_result in zip(vision_items, mcp_results):
            # MCP normalization: use MCP costs if available, else LLM estimate
            if mcp_result is not None and mcp_result.get("available"):
                cost_low = mcp_result.get("cost_low", item.estimated_cost_low)
                cost_high = mcp_result.get("cost_high", item.estimated_cost_high)
            else:
                cost_low = item.estimated_cost_low
                cost_high = item.estimated_cost_high

            # paint_complexity multiplier — cosmetic items only
            if item.repair_category.value == "cosmetic":
                cost_low = round(cost_low * paint_mult)
                cost_high = round(cost_high * paint_mult)

            vision_repair_low += cost_low
            vision_repair_high += cost_high

    history_repair_low = 0
    history_repair_high = 0
    if history_result:
        history_items = history_result.repair_mentions
        # Fire all MCP calls concurrently
        mcp_tasks = [
            call_tool(
                "get_repair_estimate",
                {
                    "make": listing.make,
                    "model": listing.model,
                    "year": listing.year,
                    "repair_type": item.component,
                },
            )
            for item in history_items
        ]
        mcp_results = await asyncio.gather(*mcp_tasks)

        for item, mcp_result in zip(history_items, mcp_results):
            # MCP normalization only — no paint multiplier for History items
            if mcp_result is not None and mcp_result.get("available"):
                cost_low = mcp_result.get("cost_low", item.estimated_cost_low)
                cost_high = mcp_result.get("cost_high", item.estimated_cost_high)
            else:
                cost_low = item.estimated_cost_low
                cost_high = item.estimated_cost_high

            history_repair_low += cost_low
            history_repair_high += cost_high

    repair_low = vision_repair_low + history_repair_low
    repair_high = vision_repair_high + history_repair_high

    # ------------------------------------------------------------------
    # 8. Finance score (deterministic)
    # ------------------------------------------------------------------
    finance_score = _compute_finance_score(
        asking_price=listing.asking_price,
        market_value=float(precomputed["estimated_market_value"]),
        range_band=precomputed["range_band"],
        total_repair_high=repair_high,
        vehicle_age_years=precomputed["vehicle_age_years"],
        mileage=listing.mileage,
    )

    # ------------------------------------------------------------------
    # 9b. LLM summary — full context now available
    # ------------------------------------------------------------------
    price_delta = precomputed["price_delta"]
    price_delta_pct = (price_delta / max(precomputed["estimated_market_value"], 1)) * 100
    summary_data = {
        "vehicle": f"{listing.year} {listing.make} {listing.model}",
        "asking_price_usd": listing.asking_price,
        "estimated_market_value_usd": f"${precomputed['estimated_market_value']:,}",
        "price_vs_market": (
            f"${abs(price_delta):,} {'above' if price_delta > 0 else 'below'} "
            f"midpoint ({price_delta_pct:+.1f}%)"
        ),
        "total_repair_cost_low_usd": f"${repair_low:,}",
        "total_repair_cost_high_usd": f"${repair_high:,}",
        "effective_all_in_cost_usd": f"${listing.asking_price + repair_high:,}",
        "vision_data_available": "yes" if vision_result else "no (visual repair costs excluded)",
        "history_data_available": "yes" if history_result else "no (text repair costs excluded)",
        "finance_score": f"{finance_score}/10",
    }
    summary = await _generate_summary(summary_data)

    return FinanceAgentResult(
        finance_score=finance_score,
        estimated_market_value=precomputed["estimated_market_value"],
        price_delta=precomputed["price_delta"],
        total_repair_cost_low=repair_low,
        total_repair_cost_high=repair_high,
        depreciation_summary=precomputed["depreciation_summary"],
        financing_vs_cash_analysis=precomputed["financing_vs_cash_analysis"],
        projected_annual_maintenance=precomputed["annual_maintenance"],
        summary=summary,
    )


async def run(
    listing: ListingInput,
    vision_result: VisionAgentResult | None,
    history_result: HistoryAgentResult | None,
    db: AsyncSession,
) -> FinanceAgentResult:
    """Convenience wrapper — runs both phases in sequence.

    Used by direct callers (tests, manual scripts) that do not need the
    LangGraph split. The orchestrator calls run_independent and run_dependent
    from separate nodes; this wrapper preserves backward compatibility.
    """
    precomputed = await run_independent(listing, db)
    return await run_dependent(listing, precomputed, vision_result, history_result)
